### ISSUE TITLE
Error on the code

### ISSUE THREAD

**Issue by NewGove** [hoaipanda/StickerMakerWhatsapp#1]
thank for submitting this project 
 i tried to run the project and  i got this error 

`2018-12-08 22:43:10.661 3630-3630/com.sticker.stickermakerwhatsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sticker.stickermakerwhatsapp, PID: 3630
    java.lang.RuntimeException: Unable to get provider com.sticker.stickermakerwhatsapp.StickerContentProvider: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:5814)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.sticker.stickermakerwhatsapp.StickerContentProvider.onCreate(StickerContentProvider.java:93)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) `

**Comment by hazarbozkurt** [comment]
:(( same me
